### ISSUE TITLE
No Having permision to install the riposo

### ISSUE THREAD

**Issue by WalidDevRes** [bukanspot/DiscordBox#2]
Hello ! I'm instaling ur cool projet, but i'm geting block because i don't have the permission to clone the ripository thanks you for your help ! <3

Ps sorry for the bad english i'm french <3 <3

![image](https://github.com/bukanspot/DiscordBox/assets/121767703/3e78fd30-eb63-4333-b3d8-bcb683be4e3a)

**Comment by bukanspot** [comment]
This problem occurred because you haven't added the SSH key from your device to your GitHub account. Try following these steps to solve your issue: https://dev.to/bukanspot/add-ssh-key-to-github-41fn
The article was written using a Linux device. Please open the reference link provided at the end of the page for solutions using a Windows device.

**Comment by WalidDevRes** [comment]
i fix the probleme i just install the zip from the interface web, but thanks you !!

**Comment by bukanspot** [comment]
> i fix the probleme i just install the zip from the interface web, but thanks you !!

Yes, you can download the source code as a zip file if you only want the source code files, but the git file is not included in the zip file. Alternatively, you can also clone via HTTPS.
